services:
#  lmaco:
#    image: lmaco
#    build:
#      context: .
#      dockerfile: LMACO/Dockerfile
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: 1111
      volumes:
        - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: